### ISSUE TITLE
Not compatible with PhpStorm 2024.2

### ISSUE THREAD

**Issue by ptyskju** [KozhanovDmytro/localstack-intellij-idea-plugin-public#2]
Hi! Unfortunately plugin is not compatible with newest version of IDE, PhpStorm 2024.2.

**Comment by KozhanovDmytro** [comment]
Hi Krzysztof, the new version has been uploaded and is currently awaiting review and approval by JetBrains. This usually takes 1-2 days, but I expect it to be ready this evening.

**Comment by KozhanovDmytro** [comment]
The new version is available for download.
