### ISSUE TITLE
Can't see lambdas in rider

### ISSUE THREAD

**Issue by armadilo** [KozhanovDmytro/localstack-intellij-idea-plugin-public#3]
I can't see my lambdas in the rider plugin (I see SQS and S3 buckets), while I do see it in localstack browse

**Comment by KozhanovDmytro** [comment]
Hello @armadilo, thank you for reaching out. The Lambda tab in the plugin is currently in beta, so it's possible that you might encounter some issues with it. We appreciate your understanding as we work to improve this feature.

Could you please confirm if the plugin is configured to the correct region where your Lambda functions are located?

**Comment by armadilo** [comment]
Thank you for the response.
Yes, I'm on the right region for sure.

**Comment by KozhanovDmytro** [comment]
Okay, I'll have a look later. As soon as I find something I'll get back to you

**Comment by KozhanovDmytro** [comment]
@armadilo just want to clarify. Do you see any errors or warning from the plugin?

**Comment by armadilo** [comment]
@KozhanovDmytro - yes, I see this: "Warning: Value cannot be null or empty!"

I'm using mac BTW

**Comment by KozhanovDmytro** [comment]
It seems that the plugin is unable to identify the runtime or package being used in your Lambda function. Could you kindly share the runtime and package you are using in your Lambda functions?

**Comment by armadilo** [comment]
I am using .net 6

**Comment by KozhanovDmytro** [comment]
Thanks for sharing, the fix will be applied in `2024.3.3` version. I'll let you know in this ticket as soon as it's available to download.

**Comment by armadilo** [comment]
Thanks!

**Comment by KozhanovDmytro** [comment]
@armadilo, the new version is available for download. Please let me know if the fix works for you.

**Comment by armadilo** [comment]
Yes, it is working! Thanks.
