### ISSUE TITLE
Enhancement: SQS message attributes

### ISSUE THREAD

**Issue by pedrosmmc** [KozhanovDmytro/localstack-intellij-idea-plugin-public#4]
The possibility to fetch along with the message, the corresponding message attributes.
This is useful to check useful metadata for business logic.

**Comment by KozhanovDmytro** [comment]
Hello Pedro, thank you for the suggestion. Will add that in the next release(s) and let you know in this ticket.

**Comment by KozhanovDmytro** [comment]
Hello @pedrosmmc, added a possibility to fetch and send messages with message attributes. Please see version `2024.4.1`
